Week7/W7D2/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

Week7/W7D2/cats/app/models/user.rb
class User < ApplicationRecord
    validates :username, :password_digest, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true }

    attr_reader :password
    
    after_initialize :ensure_session_token

    def ensure_session_token
        self.session_token ||= self.SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil unless user
        if user.is_password?(password)
            user
        else
            nil
        end
    end
    
end

Week7/W7D2/cats/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
        render :index
    end

    def new
        render :new
    end

    def edit
        render text: "We need to work on this"
    end

    def create
        @user = User.new(params.require(:user).permit(:username, :password))

        if @user.save!
            redirect_to users_url
        else
            # puts "we got here"
            # flash.now[:errors] = @user.errors.full_messages
            # render :edit
        end
    end

end

Week7/W7D2/cats/app/views/users/index.html.erb
<h1>Users upon users!</h1>

<ul>
  <% @users.each do |user| %>
    <li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
  <% end %>
</ul>

<a href="<%= new_user_url %>">Create User</a>

Week7/W7D2/cats/app/views/users/new.html.erb
<h1>Making a new User!</h1>

<form action="<%= users_url %>" method="POST">

    <label for="username">Username</label>
    <input type="text" name="user[username]" id="username">

    <br>
    
    <label for="password">Password</label>
    <input type="text" name="user[password]" id="password">

    <input type="submit" value="Create">
</form>