Week8/W8D2_Rails_Test/practice/rails_2_practice_2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :create, :new, :index] do 
    resources :goals, only: [:create, :destroy]
  end
  resources :goals, only: [:destroy]
  resource :session, only: [:new, :create, :destroy]
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/models/goal.rb
class Goal < ApplicationRecord
    validates :name, :details, presence: true 
    belongs_to :user,
        foreign_key: :user_id,
        class_name: :User 
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, :password_digest, presence: true
    validates :username, uniqueness: true 
    validates :password, length: {minimum: 6, allow_nil: true } 
    after_initialize :ensure_session_token
    attr_reader :password
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.base64(64)
        self.save
        self.session_token 
    end

    def self.find_by_credentials(username, password)
        @user = User.find_by(username: username)
        return nil if @user.nil?

        if @user.is_password?(password)
            return @user
        else
            return nil
        end
    end



    has_many :goals,
        foreign_key: :user_id,
        class_name: :Goal


    private

    def ensure_session_token
        self.session_token ||= reset_session_token!
    end

end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :signed_in?, :current_user
    
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def sign_in!(user)
        @current_user = user 
        session[:session_token] = @current_user.reset_session_token!
    end

    def sign_out! 
        current_user.reset_session_token!
        session[:session_token] = nil 
    end

    def signed_in?
        !!current_user
    end

    def require_sign_in!
        if signed_in? 
        else 
            redirect_to new_session_url 
        end
    end
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :require_sign_in!, only: [:create, :destroy]
    def create
        @goal = Goal.new(goal_params)
        @goal.user_id = params[:user_id]
        # debugger 
        if @goal.save
        else
            flash[:errors] = @goal.errors.full_messages
        end   
        redirect_to user_url(params[:user_id])
    end

    def destroy
        @goal = current_user.goals.find_by(id: params[:id])
        if @goal && @goal.delete
            redirect_to users_url
        end 
    end

    private 

    def goal_params
        params.require(:goal).permit(:name, :details, :status)
    end
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username],
        params[:user][:password])

        if @user
            sign_in!(@user)
            redirect_to users_url
        else
            flash[:errors] = ['Invalid username or password']
            render :new 
        end
    end

    def destroy
        sign_out! if signed_in?
        redirect_to new_session_url
    end
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_sign_in!, only: [:index, :show]
    def new
        @user = User.new
        render :new 
    end

    def create 
        @user = User.create(user_params)

        if @user.save
            # debugger 
            sign_in!(@user)
            redirect_to users_url
        else 
            flash[:errors] = @user.errors.full_messages 
            render :new 
        end
    end

    def index
        if signed_in?
            @users = User.all 
            render :index 
        else 
            redirect_to new_session_url
        end
    end

    def show 
        @user = User.find(params[:id])

    end

    private 
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/helpers/goals_helper.rb
module GoalsHelper
end

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/views/users/index.html.erb
<h1>All Users</h1>
<div>
    <ul>
        <li>
            <% @users.each do |user|%>
                <a href="<%= user_url(user)%>"</a>
                <%= user.username%>
            <% end %>
        </li>
    </ul>
</div>

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method = "Post">
    <input type="hidden" 
    name= "authenticity_token" 
    value="<%= form_authenticity_token%>"/>

    <label>Username
        <input name="user[username]" value="<%=@user.username%>"/>
    </label>
    <label>Password
        <input type="password" name="user[password]"/>
    </label>
    <button>Sign Up</button>
</form>

Week8/W8D2_Rails_Test/practice/rails_2_practice_2/app/views/users/show.html.erb
<div>
    <ul>
        <% @user.goals.each do |goal| %>
        <li>
            <p><%= goal.name%></p>
            <p><%= goal.details%></p>
            <p><% if goal.status%></p>
                    <p>Done</p>
                    <%end%>
            <form action="<%= goal_url(goal)%>" method="POST"/>
                <input type="hidden" 
                name="autheniticity_token" 
                value="<% form_authenticity_token%>"/>
            <button>Delete Goal</button>
        </li>
        <% end %>
    </ul>
</div>

<h1>Add a New Goal</h1> 
<form action="<%= user_goals_url(@user) %>" method="POST">
    <label>Name
        <input name="goal[name]">
    </label>
    <label>Details
        <input name="goal[details]">
    </label>

    <label> Is This Complete?
        <label>True
            <input type="radio" name="goal[status]" value="true">
        </label>
        <label>False
            <input type="radio" name="goal[status]" value="false">
        </label>
        <button>
            Create Goal
        </button>
    </label>
</form>